version: '3.9'

services:
  postgres_user:
    image: postgres:14-alpine
    ports:
      - 5021:5432
    volumes:
      - ~/apps/postgres_user:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db_user

